BEGIN;

CREATE TABLE IF NOT EXISTS public.auditoria (
    id_auditoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario varchar(120) NOT NULL,
    tabla_afectada varchar(120) NOT NULL,
    accion varchar(10) NOT NULL,
    valor_inicial jsonb,
    valor_final jsonb,
    fecha_hora timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT chk_auditoria_accion
        CHECK (accion IN ('INSERT', 'UPDATE', 'DELETE'))
);

ALTER TABLE public.cliente
    ADD COLUMN IF NOT EXISTS fec_insercion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_insercion varchar(120),
    ADD COLUMN IF NOT EXISTS fec_modificacion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_modificacion varchar(120);

ALTER TABLE public.cuenta_contable
    ADD COLUMN IF NOT EXISTS fec_insercion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_insercion varchar(120),
    ADD COLUMN IF NOT EXISTS fec_modificacion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_modificacion varchar(120);

ALTER TABLE public.asiento
    ADD COLUMN IF NOT EXISTS fec_insercion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_insercion varchar(120),
    ADD COLUMN IF NOT EXISTS fec_modificacion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_modificacion varchar(120);

ALTER TABLE public.asiento_linea
    ADD COLUMN IF NOT EXISTS fec_insercion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_insercion varchar(120),
    ADD COLUMN IF NOT EXISTS fec_modificacion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_modificacion varchar(120);

ALTER TABLE public.libro_iva_comprobante
    ADD COLUMN IF NOT EXISTS fec_insercion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_insercion varchar(120),
    ADD COLUMN IF NOT EXISTS fec_modificacion timestamp without time zone,
    ADD COLUMN IF NOT EXISTS usu_modificacion varchar(120);

COMMIT;
