# Generated by Django 5.0.2 on 2024-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
