# Generated by Django 5.0.2 on 2024-03-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_personafisica_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='cedula',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='personafisica',
            name='ruc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='ruc',
            field=models.CharField(max_length=11),
        ),
    ]
