# Generated by Django 5.0.2 on 2024-03-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_personafisica_cedula_alter_personafisica_ruc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafisica',
            name='contrasena',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='contrasena',
            field=models.CharField(default='', max_length=25),
        ),
    ]
