# Generated by Django 5.0.2 on 2024-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_personafisica_contrasena_personajuridica_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafisica',
            name='vencimiento',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='vencimiento',
            field=models.CharField(default='', max_length=10),
        ),
    ]
