# Generated by Django 5.0.2 on 2024-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_personafisica_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='cedula',
            field=models.CharField(max_length=8),
        ),
    ]
