# Generated by Django 5.0.2 on 2024-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_personafisica_ruc_alter_personajuridica_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personafisica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
