# Generated by Django 5.0.2 on 2024-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_personajuridica_direccion_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
