# Generated by Django 5.0.2 on 2024-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_personajuridica_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
